### ISSUE TITLE
Добавить возможность указания ссылки в описании модуля

### ISSUE THREAD

**Issue by Psixodelik** [hexlet-basics/hexlet-basics#307]
Есть потребность добавить ссылку на Cheatsheet в курсы по вёрстке. Лучшим местом будет описание модуля. Для этого необходимо реализовать дополнительное поле в файле `description.yml`, где можно указать имя ссылки и непосредственно саму ссылку. Например,

```yml
links:
  - name: Скачать Cheatsheet
    url: code-basics.ru/cheats.pdf
```

Вывод можно сделать сразу после описания модуля на странице курса
